### ISSUE TITLE
unexpected keyword argument "min_impurity_split"

### ISSUE THREAD

**Issue by alailang** [JanBrabec/brforest#1]
Dear JanBrabec,
DecisionTrees from scikit-learn that was used in BrForest not have paramter "min_impurity_split", BrForestClassifier come out with error of "__init__() got an unexpected keyword argument 'min_impurity_split".

**Comment by JanBrabec** [comment]
Thanks @alailang for reporting this. The parameter was removed in the recently released scikit-learn==1.0.0.

I have fixed the issue and will release a new version on pip tomorrow.

**Comment by JanBrabec** [comment]
Released version 1.0.1 which fixes the issue

**Comment by soomaiya** [comment]
Dear JanBrabec,
I am still facing this error with scikit-learn==1.0.1
TypeError: __init__() got an unexpected keyword argument 'min_impurity_split'


#Training the model
tree_clas = DecisionTreeClassifier(ccp_alpha=0.01, class_weight=None, criterion='entropy',
                       max_depth=9, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1024, splitter='best')
tree_clas.fit(x_train, y_train)
y_predict = tree_clas.predict(x_test)

**Comment by JanBrabec** [comment]
Dear [soomaiya](https://github.com/soomaiya), from you code example it seems you are having an issue with the scikit_learn library itself. I suggest to remove `min_impurity_split=None` argument from the DecisionTreeClassifier initialization.
